using System.Collections.Generic;
namespace motw {
    public static class config{
        public static List<Player> players = new List<Player>{
            // initialize players here
        };

        public static Dictionary<string, string> moves = new Dictionary<string, string>(){
            {"kicksomeass", "This is used when you are fighting something that's fighting you back. When you get into a fight and **kick some ass**, roll +Tough. On any success (i.e., total 7 or more) you inflict harm on (and suffer harm from) whatever you're fighting. On a miss, you get your ass kicked instead. The amount of harm is based on the established dangers in the game. That usually means you inflict the harm rating of your weapon and your enemies inflict their attack's harm rating on you. If you roll a 10+, choose one extra effect:\n• You gain the advantage: take +1 forward, or give +1 forward to another hunter.\n• You inflict terrible harm (+1 harm).\n• You suffer less harm (-1 harm).\n• You force them where you want them." },
            {"actunderpressure", "This covers trying to do something under conditions of particular stress or danger. Examples of acting under pressure are: staying on task while a banshee screams at you; barricading a door before the giant rats catch up; resisting the mental domination of a brain-worm; fighting on when you're badly injured.\n\nWhen you act under pressure, roll +Cool. On a 10+ you do what you set out to. On a 7-9 the Keeper is going to give you a worse outcome, hard choice, or price to pay. On a miss, things go to hell."},
            {"helpout", "When you help another hunter with a move they are making, roll +Cool.\n On a 10+ your help grants them +1 to their roll. On a 7-9 your help grants them +1 to their roll, but you also expose yourself to trouble or danger. On a failure, you expose yourself to trouble or danger without helping."},
            {"investigateamystery", "Investigating can be done any number of ways: following tracks, interviewing witnesses, forensic analysis, looking up old folklore in a library, typing the monster's name into Google, capturing the monster and conducting tests on it, and so on. Anything that might give you more information about what's going on is fair game for an investigate move.\n When you investigate a mystery, roll +Sharp. On a 10+ hold 2, and on a 7-9 hold 1. On a miss, you reveal some information to the monster or whoever you are talking to. The Keeper might ask you some questions, which you have to answer. One hold can be spent to ask the Keeper one of the following questions:\n\n• What happened here?\n• What sort of creature is it?\n• What can it do?\n• What can hurt it?\n• Where did it go?\n• What was it going to do?\n• What is being concealed here?\n\nIt's important that your attempts to investigate (and the results you get from them) are plausible and consistent with what's happening. The Keeper may ask, “how do you find that out?” If you don't have a good answer, choose another question instead. "},
            {"manipulatesomeone", "This move is used to get people to do what you want, but you need to give them a reason to do it first. What counts as a reason will depend on your relationship with the person. Maybe you've given them a reason to trust you, or you offer them a reward to do it, or maybe you have real (or faked) authority. Once you have given the target a reason, tell them what you want them to do and roll +Charm. For a normal person:\n\n• If you get 10+, then they'll do it as long as you reward them aspromised.\n• On a 7-9, they'll do it, but only if you do something for themright now to show that you mean it.\n• On a miss, your approach is completely wrong: you offend oranger the target.\n\nFor another hunter:\n• On a 10+ they mark experience and get +1 forward if they do\nwhat you ask.• On a 7-9, they mark experience if they do what you ask.\n• On a miss, it's up to that hunter to decide how badly you\noffend or annoy them. They mark experience if they do not do\nwhat you asked."},
            {"protectsomeone", "If someone is about to suffer harm and you can somehow prevent it, you can try to protect them. When you prevent harm to another character, roll +Tough. On any success (i.e., 7 or more), you protect them okay, but you'll suffer some or all of the harm they were going to get. If you got a 10+ choose an extra below. On a miss, then you end up making things worse.\n\n • You suffer little harm (-1 harm).\n • All impending danger is now focused on you.\n • You inflict harm on the enemy.\n • You hold the enemy back.\n"},
            {"readabadsituation", "When you look around and read a bad situation, roll +Sharp. On a 10+ hold 3, and on a 7-9, hold 1. One hold can be spent to ask the Keeper one of the following questions: On a miss, you might mis-read the situation (e.g. “Everything is fine here! It will be totally safe to go investigate alone!”), or you might reveal tactical details to your enemies (which means the Keeper can ask the questions above of you).\n\n • What's my best way in?\n • What's my best way out?\n • Are there any dangers we haven't noticed?\n • What's the biggest threat?\n • What's most vulnerable to me?\n • What's the best way to protect the victims?\n\n If you act on the answers, you get +1 ongoing while the information is relevant. For example, if you ask for the best way in to the monster's lair then you'll get +1 while you are infiltrating it. But once you're in, the information doesn't help you any more."},
            {"usemagic", "When you **use magic**, say what you're trying to achieve and how you do the spell, then roll +Weird. If you get a 10+, the magic works without issues: choose your effect. On a 7-9, it works imperfectly: choose your effect and a glitch. The Keeper will decide what effect the glitch has. On a miss, you lose control of the magic. This never ends well. By default the magic has one of the effects listed below, lasts for around thirty minutes, and does not expose you to danger, unwanted attention, or side-effects. If there's a glitch that might change.\n\n Effects:\n • Inflict harm (1-harm ignore-armour magic obvious).\n • Enchant a weapon. It gets +1 harm and +magic.\n • Do one thing that is beyond human limitations.\n • Bar a place or portal to a specific person or a type of creature.\n • Trap a specific person, minion, or monster.\n • Evict a spirit or curse from the person, object, or place it inhabits.\n • Summon a monster into the world.\n • Communicate with something that you do not share a language with.\n • Observe another place or time.\n • Heal 1-harm from an injury, or cure a disease, or neutralize a poison.\n\n Glitches:\n • The effect is weakened.\n • The effect is of short duration.\n • You take 1-harm ignore-armour.\n • The magic draws immediate, unwelcome attention.\n • It has a problematic side effect. The Keeper may require one or more of the following:\n • The spell requires weird materials.\n • The spell will take 10 seconds, 30 seconds, or 1 minute to cast.\n • The spell requires ritual chanting and gestures.\n • The spell requires you to draw arcane symbols.\n • You need one or two people to help cast the spell.\n • You need to refer to a tome of magic for the details.\n\n If you want to do magic that goes beyond these effects, it counts as **big magic**."},
        };
    }
}
